apiVersion: batch/v1
kind: Job
metadata:
  name: smesh-with-vms-infra-postsync
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/hook: PostSync
  labels:
    smesh-with-vms-infra-postsync: ''
spec:
  template:
    spec:
      activeDeadlineSeconds: 900
      containers:
        - image: registry.redhat.io/openshift4/ose-cli:v4.7
          command:
            - /bin/bash
            - -c
            - |
              export HOME=/tmp/cli
              echo ""
              echo -n "Waiting for Service Mesh Control Plane"
              sleep $SLEEP
              until [ $(oc get smcp/basic -n istio-system -o jsonpath='{.status.readiness.components.unready}') = '[]' ] 
              do
                echo -n "."
                sleep $SLEEP
              done
              echo -n -e "Service Mesh Control Plane Ready \n"
              echo -n "Waiting for Kubevirt Ready"
              sleep $SLEEP
              until [[ $(oc get HyperConverged/kubevirt-hyperconverged -n openshift-cnv -o jsonpath='{.status.conditions[-1:].reason}') = 'ReconcileCompleted'  &&  $(oc get HyperConverged/kubevirt-hyperconverged -n openshift-cnv -o jsonpath='{.status.conditions[-1:].status}') = 'True' ]]  
              do
                echo -n "."
                sleep $SLEEP
              done             
              echo -n -e "Kubevirt Ready \n"
          imagePullPolicy: Always
          name: oc-wait-container
          env:
            - name: SLEEP
              value: "15"
      dnsPolicy: ClusterFirst
      restartPolicy: OnFailure
      serviceAccountName: sa-job
      terminationGracePeriodSeconds: 90
